language: cpp
compiler:
- g++
os:
- linux
install:
- sudo pip install codecov
script:
- make
- ./hw1_Triangle_test
- ./hw1_NextDate_test
- ./hw1_Commission_test
- gcov -a hw1_Triangle.cc
- gcov -a hw1_NextDate.cc
- gcov -a hw1_Commission.cc
- gcov -b hw1_Triangle.cc
- gcov -b hw1_NextDate.cc
- gcov -b hw1_Commission.cc

branches:
  only:
  - master
after_success:
- codecov -t 156cc777-7356-468b-a00a-d903935b33e6 -X gcov
